### ISSUE TITLE
Enhancement: GUI emoji chooser with fuzzy searching

### ISSUE THREAD

**Issue by akaleeroy** [alexmick/emoji-to-ahk#1]
This project is off to a great start but in order for emoji entry to be usable it needs a GUI emoji chooser with fuzzy matching.

Like this one in WhatsApp Web:

![Good emoji keyboard in WhatsApp Web](https://user-images.githubusercontent.com/4068718/27206880-0414767a-5243-11e7-93fb-e756c24872e8.gif)

**Comment by alexmick** [comment]
I totally agree, the trouble is I'm not sure this is doable in AHK alone. Will have to look into it....
